use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’10.0’

target 'twitsplit' do
    pod 'SVProgressHUD'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = ‘4.0’
        end
    end
end


